dependencies {
    implementation project(':core')
    implementation project(':research-core')
    implementation project(':research-lab')
    implementation project(':replay-engine')
    implementation project(':data-analytics')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.slf4j:slf4j-api'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
