rootProject.name = 'trade-j'

include 'trade-core'
include 'trade-broker-api'
include 'trade-broker-dhan'
include 'trade-strategy'
include 'trade-execution'
include 'trade-disruptor'
include 'trade-persistence'
include 'trade-app'
include 'trade-pipeline-platform'
project(':trade-pipeline-platform').projectDir = file('pipeline/platform/trade-pipeline-platform')
