dependencies {
    implementation project(':core')
    implementation project(':broker-api')
    implementation project(':runtime-hotpath')
    implementation 'org.springframework:spring-websocket'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'org.slf4j:slf4j-api'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
    testImplementation 'ch.qos.logback:logback-classic'
    testImplementation testFixtures(project(':core'))
}
