dependencies {
    implementation project(':core')
    implementation "net.openhft:chronicle-queue:${versions.chronicleQueue}"
    implementation "org.duckdb:duckdb_jdbc:${versions.duckdb}"
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'org.slf4j:slf4j-api'

    testImplementation testFixtures(project(':core'))
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-junit-jupiter'
    testImplementation 'ch.qos.logback:logback-classic'
}
