dependencies {
    api project(':broker-api')
    api project(':core')

    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'org.slf4j:slf4j-api'
    implementation 'io.micrometer:micrometer-core'

    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
}
