dependencies {
    implementation project(':core')
    implementation project(':broker-api')
    implementation project(':trading-strategy')
    implementation project(':trading-execution')
    implementation project(':trading-simulation')
    implementation project(':data-persistence')
    implementation project(':gateway')
    implementation project(':pipeline-runtime')
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'org.slf4j:slf4j-api'

    testImplementation testFixtures(project(':core'))
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
}
