trade:
  broker-type: upstox
  upstox:
    client-id: ${upstox.sandbox.clientId}
    client-secret: ${upstox.sandbox.clientSecret}
    redirect-uri: ${upstox.sandbox.redirectUri}
    access-token: ${upstox.sandbox.accessToken:}
    analytics-only: false
    sandbox: true
    refresh-buffer-ms: 1800000
    token-expiry-buffer-ms: 600000

  storage:
    chronicle-path: runtime-dev/events
    duckdb-path: runtime-dev/data.db

spring:
  config:
    import:
      - optional:file:./config/upstox-sandbox.properties
