dependencies {
    implementation project(':core')
    implementation project(':pipeline-core')
    implementation project(':data-feature-store')
    implementation project(':trading-indicators')
    implementation project(':trading-institutional-scanner')
    implementation 'org.slf4j:slf4j-api'

    testImplementation testFixtures(project(':core'))
    testImplementation project(':data-historical-ingest')
}
