dhan.sandbox.clientId=2505162156
dhan.sandbox.accessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbkNvbnN1bWVyVHlwZSI6IlNFTEYiLCJwYXJ0bmVySWQiOiIiLCJkaGFuQ2xpZW50SWQiOiIyNTA1MTYyMTU2Iiwid2ViaG9va1VybCI6IiIsImlzcyI6ImRoYW4iLCJleHAiOjE3ODI0NTM1NzR9.isb88C9AURPnfvad0mpVRqaOeMKk2fafWVzvL2sbthaVcUnP5E6Pk9tqSQ-O1u6dmHLb3S9olCwGwa5uh__R-A
dhan.sandbox.restBaseUrl=https://sandbox.dhan.co/v2
dhan.testOrderSymbol=TCS
dhan.testOrderSecurityId=11536
dhan.testOrderSegment=NSE_EQ
dhan.testOrderExchange=NSE
dhan.testOrderQuantity=1
dhan.testOrderPricePaise=10000
