dhan.clientId=1106251237
dhan.accessToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJkaGFuIiwicGFydG5lcklkIjoiIiwiZXhwIjoxNzgxMTYwOTY2LCJpYXQiOjE3ODEwNzQ1NjYsInRva2VuQ29uc3VtZXJUeXBlIjoiQVBQIiwiZGhhbkNsaWVudElkIjoiMTEwNjI1MTIzNyJ9.7DkyvUTSUmdM4Hhpmkd4M6qm2aZ2gO2GB9a9zEz4nlLGJpa08q2U45PNT048BPDqkoFg5qY6Rd-xU5Pi-li6VA
dhan.authMode=TOTP_GENERATED
dhan.pinFile=config/dhan-pin.txt
dhan.totpSecretFile=config/dhan-totp-secret.txt
dhan.tokenStateFile=runtime/dhan-token-state.json
dhan.refreshBufferMinutes=10
dhan.testSymbol=NIFTY
dhan.testExchange=INDEX
dhan.testSecurityId=13
dhan.testSegment=IDX_I
dhan.historicalSymbol=NIFTY
dhan.historicalSecurityId=13
dhan.historicalSegment=IDX_I
dhan.historicalInstrument=INDEX
dhan.runtimeSymbol=NIFTY
dhan.runtimeSegment=IDX_I
