upstox.sandbox.clientId=2610a10c-3005-4d42-9895-7b31699d9bcb
upstox.sandbox.clientSecret=8mfba6htxn
upstox.sandbox.redirectUri=http://127.0.0.1:18080/callback
upstox.sandbox.accessToken=eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI2VkFaR1ciLCJqdGkiOiI2YTE5OTIxY2EyOGVkNDE1NmIwOTU1MDMiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaWF0IjoxNzgwMDYwNzAwLCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3ODAwOTIwMDB9.5t73Jf4hGdCRXXwHewY8wSHnd2XTck-n73Clq_UsYes
