dependencies {
    implementation project(':core')
    implementation project(':trading-strategy')
    implementation project(':trading-execution')
    implementation "com.lmax:disruptor:${versions.disruptor}"
    implementation 'org.slf4j:slf4j-api'

    testImplementation testFixtures(project(':core'))
    testImplementation project(':broker-api')
    testImplementation project(':data-persistence')
    testImplementation project(':trading-execution')
    testImplementation project(':runtime-hotpath')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'ch.qos.logback:logback-classic'
}
